### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by PlatinMTA** [spoturno/Blackjack#3]
We have conflicting indentation (look at #2). We should use only one type. We can use tabs, 4 spaces or 8 spaces.

I do prefer tabs, easier to work in Notepad++. However I'm open to new approches for Indentation.

**Comment by spoturno** [comment]
Thanks for the observation, fixed issue in https://github.com/spoturno/Blackjack/commit/6fda370b768d2b1f5b455be302fc4689ad143b91
